# Generated by Django 5.2.1 on 2025-05-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosechas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad_minima', models.FloatField(default=30.0, verbose_name='Humedad Mínima Aceptable (%)')),
                ('humedad_maxima', models.FloatField(default=70.0, verbose_name='Humedad Máxima Aceptable (%)')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Alertas',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
    ]
